String
valeriisydorov/EContainers pull request #1
Opened 2024-06-02 09:45 UTC by valeriisydorov

2024-06-02 09:45 UTC, valeriisydorov commented on EString/EString.cpp
> +    value[len] = '\0';
```suggestion
    value[len] = 0;
```

2024-06-09 19:06 UTC, KyrylSydorov requested changes

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.h
> +#define ESTRING_H
```suggestion
#pragma once
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +        capacity_length = 0;
not empty string

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +        *this = EString(rhs.data(), rhs.size());
Unoptimized

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    char str[len + 1];
```suggestion
    value_type str[len + 1];
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    size_type len = str.size();
```suggestion
    const size_type len = str.size();
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    char str[count + 1];
```suggestion
    value_type str[count + 1];
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    value[--value_length] = '\0';
exception

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +void EString::resize(size_type count, char ch) noexcept {
```suggestion
void EString::resize(size_type count, value_type ch) noexcept {
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +        value_length = count;
move out from this if/else

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    char ch;
```suggestion
    EString::value_type ch;
```

2024-06-09 19:06 UTC, KyrylSydorov commented on EString/EString.cpp
> +    return EString(lhs) + EString(rhs);
```suggestion
    return EString(std::move(lhs)) + EString(rhs);
```

2024-06-09 19:09 UTC, KyrylSydorov commented on EString/main.cpp
> +    char arr_5[] = {'D', 'o', 'n', 'a', 'l', 'd', ' ', 'K', 'n', 'u', 't', 'h'};
```suggestion
    char arr_5[] = {'D', 'o', 'n', 'a', 'l', 'd', ' ', 'K', 'n', 'u', 't', 'h'};
    char arr_5[] = "...";
```

2024-06-24 10:29 UTC, closed without merging